### ISSUE TITLE
user/project parameters

### ISSUE THREAD

**Issue by IanGBrennan** [AustralianBioCommons/nfta-launcher#2]
nfta-launcher seems to launch even when the `--project` parameter isn't provided, e.g. 
`$ python3 nfta-launcher/nfta-launcher.py --platform background --user ibrennan`
but it kicks out a warning:
`2023-12-01 17:33:20,448 - root - WARNING - We could not find the user name or the project code. This can cause unexpected behaviure if you using them in any configuration!`

If you put the `--user` parameter into the config.json file but don't specify the `--project` parameter, then the nfta-launcher fails with error:
```console
Traceback (most recent call last):
  File "nfta-launcher/nfta-launcher.py", line 326, in <module>
    main()
  File "nfta-launcher/nfta-launcher.py", line 287, in main
    args, config = validate_configurations(args)
  File "nfta-launcher/nfta-launcher.py", line 196, in validate_configurations
    config = load_config(args.config, args.platform)
  File "nfta-launcher/nfta-launcher.py", line 50, in load_config
    config_data = json.load(config_file)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 12 column 17 (char 417)`
```

Running the launcher with `--user` and `--project` parameters specified works without warning.

**Comment by ziadbkh** [comment]
should be fixed now with the latest update
